---
title: "Dashboard Steam"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(tidyverse)
library(DT)
tabela_ofertas <- read.csv("../ofertas.csv")
tabela_novidades_populares <- read.csv("../novidades.csv")
tabela_mercado <- read.csv("../mercado.csv")
```

# Loja de Jogos

Column {.sidebar}
------------------------------------------------------------------------

```{r}
sliderInput("slider",label = "Preço máximo", min = 0, max = max(tabela_novidades_populares$Preço), value = 20, step = 10)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Ofertas <a href="https://store.steampowered.com/search/?filter=topsellers&specials=1"> Clique aqui!</a>

```{r}
    renderDataTable({tabela_ofertas %>% 
    filter(`Preço` <= input$slider) %>% 
    datatable(rownames = FALSE) %>% 
    formatRound(c('Preço'),digits = 2)
    })

```

Column {data-width=500}
-----------------------------------------------------------------------

### Novidades Populares <a href="https://store.steampowered.com/explore/new/"> Clique Aqui!</a>

```{r}
renderDataTable({tabela_novidades_populares %>% 
    filter(`Preço` <= input$slider) %>% 
    datatable(rownames = FALSE) %>% 
    formatRound(c('Preço'),digits = 2)
    })
```

#  Mercado

Column {data-width=500}
---------------------------------------------------------------
### Gráfico de Itens
```{r}
ggplot(tabela_mercado) +
  aes(x = Quantidade, y = Preço) +
  geom_tile(size = 1.2) +
  scale_fill_hue(direction = 1) +
  coord_flip() +
  theme_linedraw() 
```

Column {data-width=500}
---------------------------------------------------------------
```{r}
tabela_mercado %>%
  knitr::kable()
```
